### ISSUE TITLE
Does not work with Node v6

### ISSUE THREAD

**Issue by alessioalex** [gajus/usus#10]
.. which is the LTS (still recommended for most users):

```
→ usus --url http://gajus.com
/home/alessio/.nvm/versions/node/v6.9.4/lib/node_modules/usus/dist/bin/commands/render.js:72
const handler = exports.handler = async argv => {
                                        ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Object.require (internal/module.js:20:19)
    at /home/alessio/.nvm/versions/node/v6.9.4/lib/node_modules/usus/node_modules/require-directory/index.js:76:17
    at Array.forEach (native)

```

**Comment by gajus** [comment]
Fair enough, fixed! I wasn't expecting this to pick up this fast. :-)

**Comment by colthreepv** [comment]
Still seems not working...

```shell
C:\Users\valerio>npm i -g usus

C:\Users\valerio>usus
C:\Users\valerio\AppData\Roaming\npm\node_modules\usus\node_modules\bluefeather\dist\map.js:9
const map = async (values, mapper, configuration) => {
                  ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\valerio\AppData\Roaming\npm\node_modules\usus\node_modules\bluefeather\dist\index.js:16:12)
```

**Comment by gajus** [comment]
See https://github.com/gajus/usus/issues/15

**Comment by colthreepv** [comment]
Thanks, the wording on that issue didn't seem to refer to node version.

**Comment by gajus** [comment]
This will be fixed in the next half an hour. :-)
